### ISSUE TITLE
Deploy Backend

### ISSUE THREAD

**Issue by robin-dc** [robin-dc/Inventory-Frontend#42]
Frontend developers are too lazy to run the backend localhost. Deploy your backend using vercel. 

You can find tutorials for this on youtube or Use chatgpt instead.

This article might help:
https://medium.com/@md.alishanali/how-to-deploy-your-node-js-backend-project-to-vercel-a-step-by-step-guide-f92133c3b5e2

**Comment by mikedacanay6** [comment]
wtf is that description huhu

**Comment by robin-dc** [comment]
malaki ka na

**Comment by mikedacanay6** [comment]
This is the deployed backend:

https://urs-inventory.onrender.com

try this endpoints:
/items
/items/6722ea0bdef4b1652fdba9df
